"use client"

import Image from "next/image"
import Link from "next/link"
import { Facebook, Linkedin, Phone } from "lucide-react"
import { useSbcPath } from "@/lib/sbc/use-sbc-path"
import { SBC_CONTACT } from "@/lib/sbc/content"

export default function SbcFooter(){const path=useSbcPath();return <footer className="relative mt-auto bg-[#132d63] px-4 pb-8 pt-16 text-white sm:px-6"><div aria-hidden className="absolute inset-x-0 top-0 h-8 bg-[#faf8f3] [clip-path:polygon(0_0,100%_0,100%_35%,94%_68%,88%_36%,81%_72%,74%_40%,67%_70%,59%_35%,51%_72%,43%_39%,35%_69%,27%_37%,19%_72%,10%_38%,0_70%)]"/><div className="mx-auto grid max-w-6xl gap-10 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs font-black uppercase tracking-[.16em] text-[#f5c843]">Organized by</p><div className="mt-3 flex items-center gap-3"><div className="flex items-center gap-2"><Image src="/prepskul-white.png" alt="" width={34} height={34} className="h-7 w-7 object-contain"/><span className="text-lg font-black tracking-tight">PrepSkul</span></div><span className="text-sm font-black text-white/35">×</span><Image src="/deltech-white.png" alt="DelTech Hub" width={92} height={32} className="h-7 w-auto object-contain"/></div><p className="mt-4 max-w-xs text-sm leading-6 text-white/65">A one-week AI and innovation experience for young problem-solvers.</p></div><div><h3 className="font-black uppercase tracking-wider text-[#f5c843]">Explore</h3><div className="mt-4 space-y-2 text-sm text-white/75"><Link className="block hover:text-white" href={path()}>Home</Link><Link className="block hover:text-white" href={path("/about")}>About our vision</Link><Link className="block hover:text-white" href={path("/program")}>Roadmap</Link><Link className="block hover:text-white" href={path("/faq")}>FAQ</Link><Link className="block hover:text-white" href={path("/partner")}>Partner with us</Link></div></div><div><h3 className="font-black uppercase tracking-wider text-[#f5c843]">Camp details</h3><p className="mt-4 text-sm leading-7 text-white/75">4–8 August 2026<br/>Buea onsite + online<br/>Ages 9–18<br/>Demo Day · 8 August</p></div><div><h3 className="font-black uppercase tracking-wider text-[#f5c843]">Talk to us</h3><a href={`tel:+237${SBC_CONTACT.phone}`} className="mt-4 flex items-center gap-2 text-sm"><Phone className="h-4 w-4"/>+237 {SBC_CONTACT.phoneDisplay}</a><div className="mt-5 flex gap-4"><a aria-label="PrepSkul on Facebook" href="https://facebook.com/prepskul"><Facebook/></a><a aria-label="PrepSkul on LinkedIn" href="https://linkedin.com/company/prepskul"><Linkedin/></a></div></div></div><p className="mx-auto mt-12 max-w-6xl border-t border-white/10 pt-6 text-xs text-white/45">© 2026 Summer Build Camp · PrepSkul × DelTech Hub</p></footer>}
