export type AliveLocale = "en" | "fr"

const EN = {
  nav: {
    mate: "SkulMate",
    tutors: "Tutors",
    about: "About",
    faq: "FAQ",
    signIn: "Sign in",
    tryMate: "Get started",
  },
  hero: {
    title: "Learn at the right level. Find the beauty in getting there.",
    titleLead: "Learn at the right level.",
    titleRest: "Find the beauty in getting there.",
    subtitle:
      "SkulMate, the AI tutor inside PrepSkul, meets them at the right level and stays with the work until it is theirs. When you want a person, browse tutors, then book or request based on your preferences. Live online, or at the table.",
    primary: "Get started",
    secondary: "Browse tutors",
    sessions: "sessions tutored",
    rating: "avg. session rating",
    minutes: "minutes tutored",
    statLine: "11,280+ sessions tutored · 4.8/5 avg. session rating · 174,360 minutes tutored",
    stats: [
      { value: "11,280+", label: "sessions tutored", start: 11280, suffix: "+", liveMs: 34000, liveMin: 19000, liveMax: 56000, decimals: 0 },
      { value: "4.8/5", label: "avg. session rating", start: 4.8, suffix: "/5", liveMs: 0, liveMin: 0, liveMax: 0, decimals: 1 },
      { value: "174,360", label: "minutes tutored", start: 174360, suffix: "", liveMs: 12000, liveMin: 7000, liveMax: 24000, decimals: 0 },
    ],
  },
  toolsTitle: "How a lesson with Mate feels",
  toolsLead:
    "He listens, draws the idea, and stays on the stuck point. A person joins when you want someone in the room.",
  tools: [
    {
      id: "talk",
      title: "Talk it through",
      body: "Say it out loud. Mate is already listening. Interrupt him. Type if someone else is in the room.",
      tone: "sky" as const,
      tile: "/onboard/art/tile-heart.png",
    },
    {
      id: "board",
      title: "See the idea",
      body: "He draws as you talk. A board, a picture, a check. The lesson moves with you.",
      tone: "cream" as const,
      tile: "/onboard/art/tile-pencil.png",
    },
    {
      id: "practice",
      title: "Practice the stuck point",
      body: "You work the bit that did not land. The linear equation. Photosynthesis. A BEPC essay. Not the whole chapter again.",
      tone: "yellow" as const,
      tile: "/onboard/art/tile-maths.png",
    },
    {
      id: "subjects",
      title: "Your school subjects",
      body: "From SIL to University. Maths, languages, sciences, hist-geo, philo, CS, and whatever you walk in with.",
      tone: "mint" as const,
      tile: "/onboard/art/tile-book.png",
    },
    {
      id: "track",
      title: "A picture of progress",
      body: "What is firm, what is still sticky. Parents who study get the same view for themselves.",
      tone: "peach" as const,
      tile: "/onboard/art/tile-medal.png",
    },
    {
      id: "memory",
      title: "Picks up where you stopped",
      body: "Next time, he already knows where you left off, and how you like it explained.",
      tone: "blue" as const,
      tile: "/onboard/art/tile-globe.png",
    },
  ],
  split: {
    title: "Mate first. A person when you want one.",
    body: "Talk the homework through with SkulMate. When a human hour is what the week needs, pick someone, or tell us who you are looking for.",
    siteTitle: "With Mate",
    siteItems: [
      { title: "Already listening", body: "Say it out loud. Interrupt. Type if the room is shared." },
      { title: "The idea on the board", body: "He draws as you talk. A picture, a check, the next step." },
      { title: "The bit that did not land", body: "He stays on the stuck point until it is yours." },
    ],
    appTitle: "With a person",
    appItems: [
      { title: "People you can meet", body: "Approved tutors. Maths, languages, sciences, the class you are in now." },
      { title: "Live, or at the table", body: "A class on the screen, or someone who sits with you." },
      { title: "Ask us to match you", body: "Subject, city, how you like to learn. We find the person." },
    ],
  },
  hybrid: {
    title: "Tutors who sit with you.",
    body: "Live online, or at the table. Maths, languages, sciences, and exam prep.",
    browse: "Browse tutors",
    request: "Request a tutor",
    online: "Online, live",
    onsite: "At home or school",
  },
  audienceKicker: "Students, parents, and teachers",
  audiences: [
    {
      id: "students",
      title: "Students",
      image: "/young-african-female-student-smiling.jpg",
      items: [
        { title: "Curriculum-true plans", body: "BEPC, Bac, GCE, WAEC, and the class you are in now." },
        { title: "Talk as you think", body: "Always-on voice. Type if the phone is shared." },
        { title: "A person when you need one", body: "Someone at the table, or live on the screen. The class you are in now." },
      ],
      cta: "Get started",
      href: "onboard",
      tone: "mint" as const,
    },
    {
      id: "parents",
      title: "Parents",
      image: "/african-mother-professional.jpg",
      items: [
        { title: "You study here too", body: "Your account learns. It does not spy." },
        { title: "After the session", body: "What was covered, what stuck, what to retry." },
        { title: "The whole home", body: "Invite every learner under the same roof." },
      ],
      cta: "Start as a parent",
      href: "onboard",
      tone: "sky" as const,
    },
    {
      id: "teachers",
      title: "Teachers",
      image: "/group-of-african-students-learning-together-with-t.jpg",
      items: [
        { title: "Questions before answers", body: "SkulMate is built to teach, not to dump answers." },
        { title: "Your class, one place", body: "See where the group is stuck." },
        { title: "Classrooms welcome", body: "Talk to us for school access." },
      ],
      cta: "Get in touch",
      href: "contact",
      tone: "peach" as const,
    },
  ],
  science: {
    title: "Your SkulMate, who already gets you.",
    body: "He listens how you think, remembers where you stuck, and explains it your way. Focusing questions, unique pictures, a lesson that stays with you.",
    cta: "Meet SkulMate",
  },
  cheat: {
    title: "Not a cheatbot.",
    body: "A chatbot feeds the answer. SkulMate does not. He is the PrepSkul tutor designed so the learner reasons through it.",
    cta: "See how a session works",
  },
  quotesTitle: "What families say",
  quotesTitleAccent: "about PrepSkul",
  quotes: [
    {
      name: "Kim L.",
      role: "parent of Andy, 13",
      place: "Douala, Cameroon",
      body: "My son asked if we still needed the extra human hour. SkulMate had already walked the same algebra, then a live tutor finished the practical.",
    },
    {
      name: "Tina M.",
      role: "parent of Sam, 14",
      place: "Bamenda, Cameroon",
      body: "Sam got an A on the mock. He talked it through with Mate. The onsite tutor kept the cadence on Saturday.",
    },
    {
      name: "Fongoh Raissa",
      role: "Upper Sixth",
      place: "Buea, Cameroon",
      body: "I had struggled for months. The explanation was clear, and I could interrupt without hunting for a button.",
    },
  ],
  faqLead: "A few things families ask before they start.",
  faqMoreTitle: "Have a few more questions?",
  faqMoreBody: "Tell us the class, the city, and whether SkulMate, a person, or both is the right mix.",
  faqCta: "Talk to us",
  faq: [
    {
      q: "What is PrepSkul?",
      a: "PrepSkul is the tutoring product. Learners and parents both study here. You learn with SkulMate, our in-app tutor and mascot, and with human tutors you find or request. Classes can be online live or onsite.",
    },
    {
      q: "What is SkulMate?",
      a: "SkulMate, or Mate, is the PrepSkul tutor experience. He listens without a tap, draws the idea, and asks before he answers. He is a feature of PrepSkul, not a second brand.",
    },
    {
      q: "How is SkulMate different from ChatGPT?",
      a: "General chatbots answer prompts. SkulMate tutors: it tracks the learning goal, looks for the misconception behind a mistake, and uses questions and hints so the learner reasons through it.",
    },
    {
      q: "Does my child have to talk out loud?",
      a: "Voice is the natural way, and there is no tap-to-talk button. On a shared phone they can type. They can pause, interrupt, and mix both.",
    },
    {
      q: "Can parents see how tutoring is going?",
      a: "Parents who study get their own lessons. They can also read a session summary: skills worked, what is firm, what is still sticky. The parent seat is not a spy cam.",
    },
    {
      q: "What happens if a learner brings up unsafe material?",
      a: "SkulMate turns the talk back to the lesson and does not continue unsafe threads. Serious flags can end the session so a parent can be informed.",
    },
    {
      q: "Does PrepSkul sell voice or learner data?",
      a: "No. Voice is used to tutor in the moment. We do not sell recordings. Cloud speech runs only to teach, then we keep the learning trace, not a public clip.",
    },
    {
      q: "What subjects does PrepSkul cover?",
      a: "Maths, French, English, sciences, history-geography, literature, economics, philosophy, computer science, and whatever else the learner brings. Class range is SIL / Class 1 through University.",
    },
    {
      q: "Can PrepSkul help when a student is behind?",
      a: "Yes. SkulMate starts from what they can already do, not from the chapter number. A human tutor can join online or onsite for the parts that need a person in the room.",
    },
    {
      q: "How do I find a human tutor?",
      a: "Browse Tutors to see approved people. Book a live class or someone at the table. Or request a tutor: the subject, the city, and how you like to learn, and we match you.",
    },
    {
      q: "Do I need a person as well as Mate?",
      a: "Mate can hold the week. When you want someone in the room, browse tutors and book a live class or a visit at the table. Or tell us who you are looking for, and we match you.",
    },
  ],
  find: {
    title: "Meet PrepSkul tutors.",
    lead: "Real people who teach the class you are in. Browse who is here. Book a live class, or ask us to match you.",
    recommended: "Approved tutors",
    request: "Request a tutor",
    online: "Online live class",
    onsite: "At the table",
    empty: "Browse tutors in the app, or ask us to match you.",
    openApp: "Get started",
    bookInApp: "Book a class",
  },
  cta: {
    title: "Ready to learn with PrepSkul?",
    body: "Start with Mate, or sit with a person. Live online, or at the table.",
    button: "Get started",
  },
  notebook: {
    title: "From the notebook",
    lead: "Short notes we keep updating: how Mate teaches, how to pick a class, what parents see.",
  },
  programs: {
    title: "Programs we host.",
    lead: "Two PrepSkul programs besides the weekly lesson. Same standard: the right level, and the beauty of getting there.",
    hostedTitle: "Programs we host",
    valuesTitle: "How a program is run",
    valuesLead: "The bar every PrepSkul program has to meet.",
    values: [
      { title: "Teach", body: "Questions before answers." },
      { title: "Stay", body: "The part that did not land gets the hour." },
      { title: "A person", body: "Mate for the week. A tutor when you want one." },
      { title: "Ship", body: "Each program has a date. We ran the camp. We ran the exam accelerator." },
    ],
    hosted: [
      {
        id: "sbc",
        title: "SBC",
        body: "A one-week builders' camp. Learners make with AI, work in a team, and pitch on Demo Day. Ages 9 to 18. Onsite or online.",
        href: "https://sbc.prepskul.com",
        external: true,
        cta: "See SBC",
        logo: "/sbclogo.png",
        cover: "/sbc-hero-builders-v2.webp",
        tone: "sky" as const,
      },
      {
        id: "peap",
        title: "PEAP",
        body: "The PrepSkul Exam Accelerator. Two weeks of free, focused revision for O-Level and A-Level.",
        href: "#peap",
        external: false,
        cta: "See PEAP",
        logo: "/peaplogo.jpg",
        cover: "/program2.jpg",
        tone: "blue" as const,
      },
    ],
    sbc: {
      kicker: "Innovation camp",
      done: "Last run: August 2026.",
      stats: [
        { value: "5 days", label: "One week" },
        { value: "9 to 18", label: "Ages" },
        { value: "Onsite and online", label: "Same week" },
      ],
      gallery: ["/sbc-gallery-student.webp", "/sbc-gallery-online.webp", "/sbc-gallery-vr.webp"],
      cta: "Visit SBC",
    },
    peap: {
      kicker: "Exam accelerator",
      done: "Last run: March 2026.",
      stats: [
        { value: "500+", label: "Learners" },
        { value: "2 weeks", label: "Focused revision" },
        { value: "Free", label: "No fee" },
      ],
      photo: "/program2.jpg",
      quote: "I had struggled for months. The explanation was clear, and I could interrupt without hunting for a button.",
      quoteName: "Fongoh Raissa, Upper Sixth, Buea",
      cta: "Get started",
    },
    closeTitle: "Everyday learning is still a tutor.",
    closeBody: "SBC and PEAP are intensives. The rest of the year is Mate, and a person when you want one.",
    schoolTitle: "School and exams",
    schoolBody: "Maths, sciences, Français, English, hist-geo, philo. The class you are in now, through BEPC, Bac, GCE, and WAEC.",
    beyondTitle: "Beyond the syllabus",
    beyondBody: "Code, design, public speaking. Same Mate. Same tutors. When the week needs it.",
    subjectsTitle: "What you can bring",
    subjects: [
      { title: "Maths", body: "The linear equation. The bit that did not land.", tile: "/onboard/art/tile-maths.png", tone: "yellow" as const },
      { title: "Sciences", body: "Photosynthesis. A practical. The diagram you cannot yet see.", tile: "/onboard/art/tile-flask.png", tone: "mint" as const },
      { title: "Languages", body: "Français, English, an essay, a spoken exam.", tile: "/onboard/art/tile-book.png", tone: "blue" as const },
      { title: "Code and making", body: "A first program, a poster, a talk in front of the class.", tile: "/onboard/art/tile-laptop.png", tone: "sky" as const },
    ],
    howTitle: "How a week looks",
    how: [
      { title: "Talk with Mate", body: "Say it out loud. He stays on the stuck point." },
      { title: "Find or request a person", body: "Browse tutors, or tell us who you are looking for." },
      { title: "Live, or at the table", body: "A class on the screen, or someone who sits with you." },
    ],
    mateCta: "Meet SkulMate",
    tutorsCta: "Browse tutors",
  },
}

const FR: typeof EN = {
  nav: {
    mate: "SkulMate",
    tutors: "Tuteurs",
    about: "À propos",
    faq: "FAQ",
    signIn: "Connexion",
    tryMate: "Commencer",
  },
  hero: {
    title: "Apprendre au bon niveau. Trouver la beauté du chemin.",
    titleLead: "Apprendre au bon niveau.",
    titleRest: "Trouver la beauté du chemin.",
    subtitle:
      "SkulMate, le tuteur IA dans PrepSkul, les rejoint au bon niveau et reste sur le travail jusqu’à ce que ce soit à eux. Pour une personne, parcours les tuteurs, puis réserve ou fais une demande selon tes préférences. En direct en ligne, ou à table.",
    primary: "Commencer",
    secondary: "Voir les tuteurs",
    sessions: "séances données",
    rating: "note moyenne",
    minutes: "minutes d'enseignement",
    statLine: "11 280+ séances données · 4,8/5 note moyenne · 174 360 minutes d'enseignement",
    stats: [
      { value: "11 280+", label: "séances données", start: 11280, suffix: "+", liveMs: 34000, liveMin: 19000, liveMax: 56000, decimals: 0 },
      { value: "4,8/5", label: "note moyenne", start: 4.8, suffix: "/5", liveMs: 0, liveMin: 0, liveMax: 0, decimals: 1 },
      { value: "174 360", label: "minutes d'enseignement", start: 174360, suffix: "", liveMs: 12000, liveMin: 7000, liveMax: 24000, decimals: 0 },
    ],
  },
  toolsTitle: "Une leçon avec Mate, comme ça",
  toolsLead:
    "Il écoute, dessine l’idée, et reste sur le point qui bloque. Une personne rejoint quand tu en veux une dans la pièce.",
  tools: [
    {
      id: "talk",
      title: "Parler pour comprendre",
      body: "Dis-le à voix haute. Mate écoute déjà. Coupe-le. Tape si quelqu’un d’autre est dans la pièce.",
      tone: "sky",
      tile: "/onboard/art/tile-heart.png",
    },
    {
      id: "board",
      title: "Voir l’idée",
      body: "Il dessine pendant que tu parles. Un tableau, une image, un check. La leçon avance avec toi.",
      tone: "cream",
      tile: "/onboard/art/tile-pencil.png",
    },
    {
      id: "practice",
      title: "Travailler le point qui bloque",
      body: "On retravaille le morceau qui n’a pas pris. L’équation linéaire. La photosynthèse. Un essai BEPC. Pas tout le chapitre encore une fois.",
      tone: "yellow",
      tile: "/onboard/art/tile-maths.png",
    },
    {
      id: "subjects",
      title: "Tes matières",
      body: "De la SIL à l’université. Maths, langues, sciences, hist-géo, philo, info, et ce que tu apportes.",
      tone: "mint",
      tile: "/onboard/art/tile-book.png",
    },
    {
      id: "track",
      title: "Une vue des progrès",
      body: "Ce qui tient, ce qui accroche encore. Les parents qui apprennent ont la même vue pour eux.",
      tone: "peach",
      tile: "/onboard/art/tile-medal.png",
    },
    {
      id: "memory",
      title: "On reprend où tu t’es arrêté",
      body: "La prochaine fois, il sait déjà où tu t’es arrêté, et comment tu aimes les explications.",
      tone: "blue",
      tile: "/onboard/art/tile-globe.png",
    },
  ],
  split: {
    title: "Mate d’abord. Une personne quand tu en veux une.",
    body: "Parle du devoir avec SkulMate. Quand une heure humaine est ce qu’il faut cette semaine, choisis quelqu’un, ou dis-nous qui tu cherches.",
    siteTitle: "Avec Mate",
    siteItems: [
      { title: "Déjà à l’écoute", body: "Dis-le à voix haute. Coupe-le. Tape si la pièce est partagée." },
      { title: "L’idée au tableau", body: "Il dessine pendant que tu parles. Une image, un check, l’étape suivante." },
      { title: "Le morceau qui n’a pas pris", body: "Il reste sur le point qui bloque jusqu’à ce que ce soit à toi." },
    ],
    appTitle: "Avec une personne",
    appItems: [
      { title: "Des gens à rencontrer", body: "Des tuteurs approuvés. Maths, langues, sciences, la classe où tu es." },
      { title: "En direct, ou à table", body: "Un cours à l’écran, ou quelqu’un qui s’assoit avec toi." },
      { title: "On te trouve la personne", body: "Matière, ville, comment tu aimes apprendre. On cherche pour toi." },
    ],
  },
  hybrid: {
    title: "Des tuteurs qui s’assoient avec toi.",
    body: "En direct en ligne, ou à table. Maths, langues, sciences, et la prépa d’examen.",
    browse: "Voir les tuteurs",
    request: "Demander un tuteur",
    online: "En ligne, en direct",
    onsite: "À la maison ou à l’école",
  },
  audienceKicker: "Élèves, parents, et enseignants",
  audiences: [
    {
      id: "students",
      title: "Élèves",
      image: "/young-african-female-student-smiling.jpg",
      items: [
        { title: "Des plans collés au programme", body: "BEPC, Bac, GCE, WAEC, et la classe où tu es." },
        { title: "Parler en pensant", body: "Voix toujours ouverte. Tape si le téléphone est partagé." },
        { title: "Une personne au besoin", body: "Quelqu’un à table, ou en direct à l’écran. La classe où tu es." },
      ],
      cta: "Commencer",
      href: "onboard",
      tone: "mint",
    },
    {
      id: "parents",
      title: "Parents",
      image: "/african-mother-professional.jpg",
      items: [
        { title: "Toi aussi tu étudies ici", body: "Ton compte apprend. Il ne surveille pas." },
        { title: "Après la séance", body: "Ce qui est vu, ce qui accroche, ce qu’il faut rejouer." },
        { title: "Toute la maison", body: "Invite chaque apprenant sous le même toit." },
      ],
      cta: "Commencer en parent",
      href: "onboard",
      tone: "sky",
    },
    {
      id: "teachers",
      title: "Enseignants",
      image: "/group-of-african-students-learning-together-with-t.jpg",
      items: [
        { title: "Des questions avant les réponses", body: "SkulMate enseigne. Il ne dump pas la réponse." },
        { title: "La classe au même endroit", body: "Voir où le groupe bloque." },
        { title: "Les salles de classe", body: "Écris-nous pour un accès école." },
      ],
      cta: "Nous écrire",
      href: "contact",
      tone: "peach",
    },
  ],
  science: {
    title: "Ton SkulMate, qui te comprend déjà.",
    body: "Il écoute comment tu penses, retient où ça bloque, et explique à ta façon. Des questions, des images uniques, une leçon qui reste avec toi.",
    cta: "Rencontrer SkulMate",
  },
  cheat: {
    title: "Pas un cheatbot.",
    body: "Un chatbot donne la réponse. SkulMate non. C’est le tuteur PrepSkul conçu pour faire raisonner.",
    cta: "Voir une séance",
  },
  quotesTitle: "Ce que disent les familles",
  quotesTitleAccent: "sur PrepSkul",
  quotes: [
    {
      name: "Kim L.",
      role: "parent d’Andy, 13 ans",
      place: "Douala, Cameroun",
      body: "Mon fils a demandé si on gardait l’heure humaine. SkulMate avait déjà défait la même algèbre, puis un tuteur live a fini le TP.",
    },
    {
      name: "Tina M.",
      role: "parent de Sam, 14 ans",
      place: "Bamenda, Cameroun",
      body: "Sam a eu un A au mock. Il a parlé avec Mate. Le tuteur sur place a tenu le rythme le samedi.",
    },
    {
      name: "Fongoh Raissa",
      role: "Upper Sixth",
      place: "Buea, Cameroun",
      body: "Je bloquais depuis des mois. L’explication était claire, et je pouvais couper sans chercher un bouton.",
    },
  ],
  faqLead: "Quelques questions avant de commencer.",
  faqMoreTitle: "Encore une question ?",
  faqMoreBody: "Dis-nous la classe, la ville, et si SkulMate, une personne, ou les deux est le bon mélange.",
  faqCta: "Nous écrire",
  faq: [
    {
      q: "Qu’est-ce que PrepSkul ?",
      a: "PrepSkul est le produit de tutorat. Les élèves et les parents étudient ici. Tu apprends avec SkulMate, le tuteur et la mascotte dans l’app, et avec des tuteurs humains que tu trouves ou demandes. Cours en ligne en direct ou sur place.",
    },
    {
      q: "Qu’est-ce que SkulMate ?",
      a: "SkulMate, ou Mate, est l’expérience tuteur de PrepSkul. Il écoute sans tapoter, dessine l’idée, et pose une question avant de répondre. C’est une fonction de PrepSkul, pas une seconde marque.",
    },
    {
      q: "En quoi SkulMate est différent de ChatGPT ?",
      a: "Un chatbot répond à une consigne. SkulMate tutorise: il suit le but, cherche le malentendu derrière l’erreur, et fait raisonner par questions et indices.",
    },
    {
      q: "L’enfant doit-il parler à voix haute ?",
      a: "La voix est la voie naturelle, sans bouton pour démarrer. Sur un téléphone partagé, on tape. On peut couper, pauser, mélanger.",
    },
    {
      q: "Les parents voient-ils comment ça se passe ?",
      a: "Les parents qui étudient ont leurs propres leçons. Ils peuvent aussi lire un résumé: compétences, ce qui tient, ce qui accroche. Ce n’est pas une caméra.",
    },
    {
      q: "Et si le propos devient inapproprié ?",
      a: "SkulMate ramène à la leçon et n’enchaîne pas. Un signal grave peut clôturer la séance pour qu’un parent soit prévenu.",
    },
    {
      q: "Vous vendez la voix ou les données ?",
      a: "Non. La voix sert à tutoriser sur le moment. Pas de vente d’enregistrements.",
    },
    {
      q: "Quelles matières PrepSkul couvre-t-il ?",
      a: "Maths, français, anglais, sciences, hist-géo, littérature, éco, philo, info, et le reste. De la SIL / Class 1 à l’université.",
    },
    {
      q: "PrepSkul aide-t-il un élève en retard ?",
      a: "Oui. SkulMate part de ce qu’il sait déjà faire. Un tuteur humain peut rejoindre en ligne ou sur place.",
    },
    {
      q: "Comment trouver un tuteur humain ?",
      a: "Parcours Tuteurs pour voir les personnes approuvées. Réserve un cours live ou quelqu’un à table. Ou demande un tuteur: la matière, la ville, et comment tu aimes apprendre, et on te trouve la personne.",
    },
    {
      q: "Faut-il une personne en plus de Mate ?",
      a: "Mate peut tenir la semaine. Quand tu veux quelqu’un dans la pièce, parcours les tuteurs et réserve un cours live ou une visite à table. Ou dis-nous qui tu cherches, et on te trouve la personne.",
    },
  ],
  find: {
    title: "Les tuteurs PrepSkul.",
    lead: "De vraies personnes qui enseignent la classe où tu es. Parcours qui est là. Réserve un cours live, ou demande-nous de te trouver quelqu’un.",
    recommended: "Tuteurs approuvés",
    request: "Demander un tuteur",
    online: "Cours en ligne",
    onsite: "À table",
    empty: "Parcours les tuteurs dans l’app, ou demande-nous de te trouver quelqu’un.",
    openApp: "Commencer",
    bookInApp: "Réserver un cours",
  },
  cta: {
    title: "Prêt à apprendre avec PrepSkul ?",
    body: "Commence avec Mate, ou assieds-toi avec une personne. En direct en ligne, ou à table.",
    button: "Commencer",
  },
  notebook: {
    title: "Du carnet",
    lead: "Des notes qu’on met à jour: comment Mate enseigne, comment choisir un cours, ce que voient les parents.",
  },
  programs: {
    title: "Les programmes que nous menons.",
    lead: "Deux programmes PrepSkul hors de la leçon de la semaine. Même exigence: le bon niveau, et la beauté du chemin.",
    hostedTitle: "Les programmes que nous menons",
    valuesTitle: "Comment un programme est mené",
    valuesLead: "L’exigence de chaque programme PrepSkul.",
    values: [
      { title: "Enseigner", body: "Des questions avant les réponses." },
      { title: "Rester", body: "Le morceau qui n’a pas pris a l’heure." },
      { title: "Une personne", body: "Mate pour la semaine. Un tuteur quand tu en veux un." },
      { title: "Livrer", body: "Chaque programme a une date. On a mené le camp. On a mené l’accélérateur d’examens." },
    ],
    hosted: [
      {
        id: "sbc",
        title: "SBC",
        body: "Un camp d’une semaine pour construire. Les jeunes font avec l’IA, travaillent en équipe, et pitchent le Demo Day. 9 à 18 ans. Sur place ou en ligne.",
        href: "https://sbc.prepskul.com",
        external: true,
        cta: "Voir SBC",
        logo: "/sbclogo.png",
        cover: "/sbc-hero-builders-v2.webp",
        tone: "sky" as const,
      },
      {
        id: "peap",
        title: "PEAP",
        body: "L’accélérateur d’examens PrepSkul. Deux semaines de révision ciblée, gratuites, O-Level et A-Level.",
        href: "#peap",
        external: false,
        cta: "Voir PEAP",
        logo: "/peaplogo.jpg",
        cover: "/program2.jpg",
        tone: "blue" as const,
      },
    ],
    sbc: {
      kicker: "Camp d’innovation",
      done: "Dernière édition: août 2026.",
      stats: [
        { value: "5 jours", label: "Une semaine" },
        { value: "9 to 18", label: "Âges" },
        { value: "Sur place et en ligne", label: "La même semaine" },
      ],
      gallery: ["/sbc-gallery-student.webp", "/sbc-gallery-online.webp", "/sbc-gallery-vr.webp"],
      cta: "Ouvrir SBC",
    },
    peap: {
      kicker: "Accélérateur d’examens",
      done: "Dernière édition: mars 2026.",
      stats: [
        { value: "500+", label: "Apprenants" },
        { value: "2 semaines", label: "Révision ciblée" },
        { value: "Gratuit", label: "Sans frais" },
      ],
      photo: "/program2.jpg",
      quote: "Je bloquais depuis des mois. L’explication était claire, et je pouvais interrompre sans chercher un bouton.",
      quoteName: "Fongoh Raissa, Upper Sixth, Buea",
      cta: "Commencer",
    },
    closeTitle: "Au quotidien, il faut encore un tuteur.",
    closeBody: "SBC et PEAP sont des intensifs. Le reste de l’année, c’est Mate, et une personne quand tu en veux une.",
    schoolTitle: "École et examens",
    schoolBody: "Maths, sciences, Français, English, hist-géo, philo. La classe où tu es, jusqu’au BEPC, Bac, GCE, et WAEC.",
    beyondTitle: "Au-delà du programme",
    beyondBody: "Code, design, prise de parole. Le même Mate. Les mêmes tuteurs. Quand la semaine en a besoin.",
    subjectsTitle: "Ce que tu peux apporter",
    subjects: [
      { title: "Maths", body: "L’équation linéaire. Le morceau qui n’a pas pris.", tile: "/onboard/art/tile-maths.png", tone: "yellow" as const },
      { title: "Sciences", body: "La photosynthèse. Un TP. Le schéma que tu ne vois pas encore.", tile: "/onboard/art/tile-flask.png", tone: "mint" as const },
      { title: "Langues", body: "Français, English, un essai, un oral.", tile: "/onboard/art/tile-book.png", tone: "blue" as const },
      { title: "Code et faire", body: "Un premier programme, une affiche, un oral devant la classe.", tile: "/onboard/art/tile-laptop.png", tone: "sky" as const },
    ],
    howTitle: "Une semaine, comme ça",
    how: [
      { title: "Parler avec Mate", body: "Dis-le à voix haute. Il reste sur le point qui bloque." },
      { title: "Trouver ou demander une personne", body: "Parcours les tuteurs, ou dis-nous qui tu cherches." },
      { title: "En direct, ou à table", body: "Un cours à l’écran, ou quelqu’un qui s’assoit avec toi." },
    ],
    mateCta: "Rencontrer SkulMate",
    tutorsCta: "Voir les tuteurs",
  },
}

export function aliveCopy(locale: string) {
  return locale.startsWith("fr") ? FR : EN
}
