import type { Locale } from "@/lib/i18n"

const siteContent = {
  en: {
    nav: {
      learn: "How it works",
      programs: "Programs",
      skulmate: "SkulMate",
      schools: "For Schools",
      impact: "Impact",
      about: "About",
      tutor: "Become a Tutor",
      cta: "Get guidance",
    },
    hero: {
      eyebrow: "Guided learning for every learner",
      title: "From classroom teaching to real understanding.",
      body: "PrepSkul combines trusted tutors, personalized learning tools, and practical programs to help every learner understand difficult concepts, build confidence, and keep progressing.",
      primary: "Find learning support",
      secondary: "Explore programs",
      trust: ["Tutor screening", "Home & online", "English & French"],
      imageAlt: "A PrepSkul tutor helping a learner review a lesson with a notebook and SkulMate wristband",
    },
    problem: {
      eyebrow: "The understanding gap",
      title: "One classroom lesson. Many different learners.",
      body: "A lesson must often move at one pace. Learners do not. When one concept is missed, the gap can follow a learner into the next topic, the next test, and the next school year.",
      quote: "PrepSkul stays with the learner beyond the lesson until the next step is clear.",
    },
    loop: {
      eyebrow: "How PrepSkul guides learning",
      title: "A clear path from difficulty to progress.",
      body: "Every PrepSkul experience follows the same learner-first loop, whether support comes from a tutor, a program, or SkulMate.",
      steps: [
        { number: "01", title: "Understand", body: "Start with the learner’s level, goal, context, and real learning challenge." },
        { number: "02", title: "Guide", body: "Choose the right tutor, program, learning tool, and next step." },
        { number: "03", title: "Practise", body: "Turn explanations into purposeful questions, projects, and revision." },
        { number: "04", title: "Progress", body: "Build confidence, see what is improving, and decide what comes next." },
      ],
    },
    pathways: {
      eyebrow: "Choose your pathway",
      title: "The right kind of support, at the right moment.",
      body: "Start with what the learner needs today. PrepSkul connects each goal to a practical next step.",
      items: [
        { title: "Personalized tutoring", body: "Find guided academic or skills support at home, online, or in a small group.", cta: "Find a tutor", href: "https://app.prepskul.com", image: "/images/site-2026/tutoring-home-session.webp", alt: "A tutor guiding a learner through mathematics during a home session" },
        { title: "Programs & experiences", body: "Build, revise, collaborate, and prepare through SBC, PEAP, and focused workshops.", cta: "Explore programs", href: "/programs", image: "/images/site-2026/sbc-build-workshop.webp", alt: "Young learners collaborating on a technology prototype" },
        { title: "SkulMate", body: "A learning companion designed to help learners revisit lessons, practise, and keep growing.", cta: "Discover the concept", href: "#skulmate", image: "/images/site-2026/skulmate-product-hero.webp", alt: "Matte-black SkulMate learning wristband and charging case" },
      ],
    },
    skulmate: {
      badge: "Product concept · In development",
      title: "Meet SkulMate.",
      subtitle: "Your learning companion for every lesson.",
      body: "SkulMate is being designed to bridge classroom teaching and individual understanding, helping a learner stay present in class, revisit what was taught, and receive support at the right level.",
      imageAlt: "A learner wearing SkulMate while listening to a teacher in class",
      productAlt: "SkulMate wristband shown with its charging case and sensors",
      steps: ["Stay present in class", "Capture the learning context", "Revisit difficult concepts", "Practise with purpose", "Keep progressing"],
      cta: "Follow SkulMate updates",
      note: "Concept visuals. Final capabilities, privacy controls, and availability will be published before launch.",
    },
    programs: {
      eyebrow: "Programs that become proof",
      title: "Learning experiences built around real outcomes.",
      body: "Each program has a clear audience, purpose, current status, and next step. Completed editions remain visible as part of PrepSkul’s learning record.",
      sbc: { status: "2026 cohort · Registration closed", title: "Summer Build Camp", body: "Six weeks of AI and entrepreneurship for young innovators aged 10 to 17 in Buea and online.", cta: "View the 2026 program", alt: "Young learners and mentors building a technology prototype during a workshop" },
      peap: { status: "2026 edition · Completed", title: "Exam Accelerator Program", body: "A focused national revision initiative designed to turn exam anxiety into structured preparation and confidence.", cta: "Explore PEAP", alt: "Learners collaborating during a tutor-led exam revision class" },
    },
    schools: {
      eyebrow: "For schools and organizations",
      title: "Extend learning support beyond the classroom.",
      body: "PrepSkul works with schools, communities, NGOs, and sponsors to design tutoring support, revision initiatives, practical learning programs, and responsible learning technology pilots.",
      points: ["Defined learner goals", "Safeguarding-first delivery", "Clear roles and reporting", "Programs adapted to context"],
      cta: "Start a partnership conversation",
      alt: "A school leader, teacher, and PrepSkul partner reviewing a learner-support plan",
    },
    trust: {
      eyebrow: "Trust before scale",
      title: "Learning support should be safe, clear, and accountable.",
      body: "We are strengthening how PrepSkul verifies tutors, protects learners, documents programs, and publishes impact. Public claims and stories should always be traceable to real evidence and consent.",
      items: [
        { title: "Tutor standards", body: "Selection, training, and expectations designed around learner safety and teaching quality." },
        { title: "Safeguarding", body: "Policies and conduct standards for tutors, learners, parents, and partners." },
        { title: "Honest evidence", body: "Program status, results, images, and stories should be current, consented, and verifiable." },
      ],
      policy: "Read our safeguarding policy",
    },
    finalCta: {
      title: "What does the learner need next?",
      body: "Tell us the goal. We’ll help you find the clearest route through tutoring, a PrepSkul program, or the right conversation with our team.",
      primary: "Find learning support",
      secondary: "Talk to PrepSkul",
    },
    footer: {
      description: "Tutors, programs and learning technology that help difficult lessons finally make sense.",
      learn: "Learn",
      programs: "Programs",
      company: "Company",
      trust: "Trust & support",
      tutoring: "Tutoring",
      online: "Online learning",
      home: "Home tutoring",
      schoolPrograms: "School partnerships",
      contact: "Contact",
      rights: "All rights reserved.",
    },
  },
  fr: {
    nav: {
      learn: "Comment ça marche",
      programs: "Programmes",
      skulmate: "SkulMate",
      schools: "Pour les écoles",
      impact: "Impact",
      about: "À propos",
      tutor: "Devenir tuteur",
      cta: "Être guidé",
    },
    hero: {
      eyebrow: "Un apprentissage guidé pour chaque apprenant",
      title: "De l’enseignement en classe à une vraie compréhension.",
      body: "PrepSkul combine des tuteurs de confiance, des outils d’apprentissage personnalisés et des programmes pratiques pour aider chaque apprenant à comprendre, gagner en confiance et progresser.",
      primary: "Trouver un soutien",
      secondary: "Explorer les programmes",
      trust: ["Tuteurs sélectionnés", "À domicile et en ligne", "Anglais et français"],
      imageAlt: "Un tuteur PrepSkul aide un apprenant avec un cahier et le bracelet SkulMate",
    },
    problem: {
      eyebrow: "L’écart de compréhension",
      title: "Une leçon en classe. Des apprenants tous différents.",
      body: "Une leçon avance souvent à un seul rythme. Les apprenants, non. Lorsqu’une notion échappe, l’écart peut suivre l’apprenant au chapitre suivant, au prochain examen et à l’année suivante.",
      quote: "PrepSkul reste aux côtés de l’apprenant après la leçon, jusqu’à ce que la prochaine étape soit claire.",
    },
    loop: {
      eyebrow: "Comment PrepSkul guide l’apprentissage",
      title: "Un chemin clair de la difficulté au progrès.",
      body: "Chaque expérience PrepSkul suit la même démarche centrée sur l’apprenant, avec un tuteur, un programme ou SkulMate.",
      steps: [
        { number: "01", title: "Comprendre", body: "Commencer par le niveau, l’objectif, le contexte et la difficulté réelle." },
        { number: "02", title: "Guider", body: "Choisir le bon tuteur, programme, outil et la prochaine étape." },
        { number: "03", title: "Pratiquer", body: "Transformer les explications en exercices, projets et révisions utiles." },
        { number: "04", title: "Progresser", body: "Gagner en confiance, observer les progrès et décider de la suite." },
      ],
    },
    pathways: {
      eyebrow: "Choisissez votre parcours",
      title: "Le bon soutien, au bon moment.",
      body: "Partons du besoin actuel de l’apprenant. PrepSkul relie chaque objectif à une prochaine étape concrète.",
      items: [
        { title: "Tutorat personnalisé", body: "Trouvez un accompagnement scolaire ou pratique à domicile, en ligne ou en petit groupe.", cta: "Trouver un tuteur", href: "https://app.prepskul.com", image: "/images/site-2026/tutoring-home-session.webp", alt: "Une tutrice accompagne une apprenante en mathématiques à domicile" },
        { title: "Programmes et expériences", body: "Construisez, révisez et collaborez grâce à SBC, PEAP et nos ateliers ciblés.", cta: "Explorer les programmes", href: "/programs", image: "/images/site-2026/sbc-build-workshop.webp", alt: "De jeunes apprenants collaborent sur un prototype technologique" },
        { title: "SkulMate", body: "Un compagnon d’apprentissage conçu pour revoir les leçons, pratiquer et continuer à progresser.", cta: "Découvrir le concept", href: "#skulmate", image: "/images/site-2026/skulmate-product-hero.webp", alt: "Bracelet d’apprentissage SkulMate et son boîtier de charge" },
      ],
    },
    skulmate: {
      badge: "Concept produit · En développement",
      title: "Découvrez SkulMate.",
      subtitle: "Votre compagnon pour chaque leçon.",
      body: "SkulMate est conçu pour rapprocher l’enseignement en classe de la compréhension individuelle, en aidant l’apprenant à rester attentif, revoir les notions et recevoir un soutien adapté.",
      imageAlt: "Un apprenant portant SkulMate écoute son enseignant en classe",
      productAlt: "Bracelet SkulMate avec son boîtier de charge et ses capteurs",
      steps: ["Rester attentif en classe", "Saisir le contexte d’apprentissage", "Revoir les notions difficiles", "Pratiquer avec un objectif", "Continuer à progresser"],
      cta: "Suivre les actualités SkulMate",
      note: "Visuels conceptuels. Les fonctionnalités finales, la confidentialité et la disponibilité seront publiées avant le lancement.",
    },
    programs: {
      eyebrow: "Des programmes qui prouvent notre action",
      title: "Des expériences construites autour de résultats concrets.",
      body: "Chaque programme présente son public, son objectif, son statut et sa prochaine étape. Les éditions terminées restent visibles dans l’histoire de PrepSkul.",
      sbc: { status: "Cohorte 2026 · Inscriptions closes", title: "Summer Build Camp", body: "Six semaines d’IA et d’entrepreneuriat pour les jeunes innovateurs de 10 à 17 ans, à Buea et en ligne.", cta: "Voir le programme 2026", alt: "De jeunes apprenants et mentors construisent un prototype technologique" },
      peap: { status: "Édition 2026 · Terminée", title: "Programme d’accélération aux examens", body: "Une initiative nationale de révision pour transformer l’anxiété en préparation structurée et en confiance.", cta: "Découvrir PEAP", alt: "Des apprenants collaborent pendant une séance de révision guidée" },
    },
    schools: {
      eyebrow: "Pour les écoles et organisations",
      title: "Prolongez le soutien au-delà de la classe.",
      body: "PrepSkul collabore avec les écoles, communautés, ONG et sponsors pour concevoir du tutorat, des révisions, des programmes pratiques et des pilotes responsables de technologie éducative.",
      points: ["Objectifs clairs", "Protection des apprenants", "Rôles et rapports définis", "Programmes adaptés au contexte"],
      cta: "Parler d’un partenariat",
      alt: "Une direction d’école, une enseignante et un partenaire PrepSkul examinent un plan d’accompagnement",
    },
    trust: {
      eyebrow: "La confiance avant l’échelle",
      title: "Le soutien scolaire doit être sûr, clair et responsable.",
      body: "Nous renforçons la sélection des tuteurs, la protection des apprenants, la documentation des programmes et la publication de l’impact. Chaque affirmation publique doit être traçable et consentie.",
      items: [
        { title: "Standards des tuteurs", body: "Sélection, formation et attentes centrées sur la sécurité et la qualité pédagogique." },
        { title: "Protection", body: "Politiques et règles de conduite pour tuteurs, apprenants, parents et partenaires." },
        { title: "Preuves honnêtes", body: "Statuts, résultats, images et témoignages actuels, consentis et vérifiables." },
      ],
      policy: "Lire notre politique de protection",
    },
    finalCta: {
      title: "De quoi l’apprenant a-t-il besoin maintenant ?",
      body: "Expliquez-nous l’objectif. Nous vous aiderons à choisir entre un tuteur, un programme PrepSkul ou la bonne conversation avec notre équipe.",
      primary: "Trouver un soutien",
      secondary: "Parler à PrepSkul",
    },
    footer: {
      description: "Des tuteurs, des programmes et une technologie éducative qui rendent les leçons difficiles plus claires.",
      learn: "Apprendre",
      programs: "Programmes",
      company: "Entreprise",
      trust: "Confiance et soutien",
      tutoring: "Tutorat",
      online: "Apprentissage en ligne",
      home: "Tutorat à domicile",
      schoolPrograms: "Partenariats scolaires",
      contact: "Contact",
      rights: "Tous droits réservés.",
    },
  },
} as const

export function getSiteContent(locale: Locale) {
  return siteContent[locale]
}
