"use client"

import Image from "next/image"
import Link from "next/link"
import { ArrowRight, Globe2, HeartHandshake, Lightbulb, Network, Rocket, Target, Users, WandSparkles } from "lucide-react"
import SbcHeader from "@/components/sbc/sbc-header"
import SbcFooter from "@/components/sbc/sbc-footer"
import { SbcPageShell } from "@/components/sbc/sbc-page-shell"
import { Doodle, Eyebrow, PaperButton, PaperSheet, Tape, TornDivider } from "@/components/sbc/paper-ui"
import { ScrollReveal } from "@/components/sbc/scroll-reveal"
import { useSbcPath } from "@/lib/sbc/use-sbc-path"
import { useSbcLanguage } from "@/lib/sbc/i18n"

const beliefs = [
  { icon: Lightbulb, title: "Ideas belong to everyone", text: "A child does not need years of technical training before they can notice a problem, imagine a solution and begin building.", tone: "yellow" as const },
  { icon: WandSparkles, title: "AI should expand agency", text: "We teach young people to use AI as a thoughtful co-builder—not as a shortcut that replaces curiosity, judgment or original thinking.", tone: "blue" as const },
  { icon: HeartHandshake, title: "Confidence grows through doing", text: "Learners build, test, collaborate and present. Real work creates a deeper kind of confidence than theory alone.", tone: "mint" as const },
]

const pathway = [
  { year: "2026", title: "Prove the experience", text: "Launch a focused Buea and online cohort, refine the five-day builder journey and set a high standard for practical youth innovation." },
  { year: "2027", title: "Reach more communities", text: "Work with schools, hubs and youth organizations so the same experience can reach learners beyond one city." },
  { year: "2028–29", title: "Build the alumni engine", text: "Invite returning builders into advanced challenges, peer communities and junior mentorship roles." },
  { year: "2030", title: "10,000 young innovators", text: "Grow a connected African community of young people who can identify problems, build responsibly and communicate their ideas." },
]

export default function AboutSbcPage() {
  const path = useSbcPath()
  const { t } = useSbcLanguage()
  return <SbcPageShell><SbcHeader/><main>
    <section className="relative overflow-hidden px-4 pb-20 pt-12 sm:px-6 lg:pb-28 lg:pt-20"><div className="mx-auto grid max-w-6xl items-center gap-12 lg:grid-cols-[1.08fr_.92fr]"><ScrollReveal><Eyebrow>Why Summer Build Camp exists</Eyebrow><h1 className="sbc-display mt-5 text-[2.65rem] font-black uppercase leading-[.92] text-[#132d63] min-[375px]:text-5xl sm:text-7xl lg:text-[5.4rem]">{t("From technology")} <span className="text-[#2864d7]">{t("consumers")}</span> {t("to confident")} <span className="text-[#168c91]">{t("builders.")}</span></h1><p className="mt-7 max-w-2xl text-base leading-7 text-slate-600 sm:text-lg sm:leading-8">SBC exists to help African young people see themselves as capable problem-solvers—not someday, but now. We give them the tools, guidance and room to turn curiosity into something real.</p></ScrollReveal><ScrollReveal delay={.08} className="relative"><Doodle className="-right-3 -top-7 rotate-12 text-5xl text-[#f2b91f]">✦</Doodle><PaperSheet className="p-3" rotate={2}><Tape className="-top-4 left-1/2 -translate-x-1/2"/><Image src="/sbc-hero-builders-v2.webp" alt="African teenagers collaborating on a technology project" width={1792} height={875} sizes="(max-width: 1024px) 92vw, 42vw" className="h-[280px] w-full rounded-[18px] object-cover min-[375px]:h-[320px] sm:h-[360px]"/></PaperSheet><PaperSheet tone="yellow" className="relative z-10 mx-auto -mt-8 w-[92%] p-4 text-center sm:-mt-10 sm:w-[88%] sm:p-5" rotate={-2}><p className="sbc-display text-xl font-black uppercase leading-tight sm:text-2xl">The future is not something children should only prepare for.</p><p className="mt-2 text-sm font-bold text-[#168c91]">They should help build it.</p></PaperSheet></ScrollReveal></div></section>

    <TornDivider/>
    <section className="bg-[#fffdf7] px-4 py-20 sm:px-6 lg:py-28"><div className="mx-auto max-w-6xl"><ScrollReveal className="mx-auto max-w-3xl text-center"><Eyebrow>Our north star</Eyebrow><p className="sbc-display mt-6 text-7xl font-black leading-none text-[#2864d7] sm:text-9xl">10K</p><h2 className="sbc-display mt-2 text-3xl font-black uppercase text-[#132d63] sm:text-5xl">Young innovators by 2030</h2><p className="mx-auto mt-6 max-w-2xl leading-8 text-slate-600">Not simply 10,000 children who attended a camp. We are building toward 10,000 young people who can recognize meaningful problems, work with others, use modern tools responsibly and stand behind what they create.</p></ScrollReveal><div className="mt-14 grid gap-5 md:grid-cols-3">{beliefs.map(({icon:Icon,title,text,tone},i)=><ScrollReveal key={title} delay={i*.06}><PaperSheet tone={tone} className="h-full p-7" rotate={i===1?1:-1}><Icon className="h-10 w-10 text-[#132d63]"/><h3 className="mt-5 text-xl font-black uppercase leading-tight">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{text}</p></PaperSheet></ScrollReveal>)}</div></div></section>

    <section className="bg-[#132d63] px-4 py-20 text-white sm:px-6 lg:py-28"><div className="mx-auto max-w-6xl"><ScrollReveal className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><Eyebrow>The bigger system</Eyebrow><h2 className="sbc-display mt-5 text-4xl font-black uppercase leading-none sm:text-6xl">{t("A camp is the")} <span className="text-[#f5c843]">{t("starting line.")}</span></h2><p className="mt-6 leading-8 text-white/70">The long-term vision is a community that compounds: learners return, alumni guide new builders, projects grow beyond Demo Day and local ecosystems discover young talent early.</p></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-[24px] border border-white/15 p-6"><Users className="h-8 w-8 text-[#f5c843]"/><h3 className="mt-4 font-black uppercase">Learners become alumni</h3><p className="mt-2 text-sm leading-6 text-white/65">Every cohort joins a growing network of young African builders.</p></div><div className="rounded-[24px] border border-white/15 p-6"><Network className="h-8 w-8 text-[#70d0cf]"/><h3 className="mt-4 font-black uppercase">Alumni become mentors</h3><p className="mt-2 text-sm leading-6 text-white/65">Experienced learners return to encourage and guide the next cohort.</p></div><div className="rounded-[24px] border border-white/15 p-6"><Rocket className="h-8 w-8 text-[#f5c843]"/><h3 className="mt-4 font-black uppercase">Projects keep moving</h3><p className="mt-2 text-sm leading-6 text-white/65">Promising ideas receive visibility, feedback and paths to further support.</p></div><div className="rounded-[24px] border border-white/15 p-6"><Globe2 className="h-8 w-8 text-[#70d0cf]"/><h3 className="mt-4 font-black uppercase">Communities connect</h3><p className="mt-2 text-sm leading-6 text-white/65">Schools, hubs, families and partners form a stronger innovation ecosystem.</p></div></div></ScrollReveal></div></section>

    <section className="px-4 py-20 sm:px-6 lg:py-28"><div className="mx-auto max-w-6xl"><ScrollReveal className="max-w-3xl"><Eyebrow>How we get there</Eyebrow><h2 className="sbc-display mt-5 text-4xl font-black uppercase sm:text-6xl">Build carefully. Learn openly. Grow together.</h2></ScrollReveal><div className="mt-12 grid gap-5 lg:grid-cols-4">{pathway.map((step,i)=><ScrollReveal key={step.year} delay={i*.05}><PaperSheet className="h-full p-6" tone={(["blue","lilac","mint","yellow"] as const)[i]} rotate={i%2?1:-1}><span className="sbc-display text-3xl font-black text-[#2864d7]">{step.year}</span><h3 className="mt-4 text-lg font-black uppercase leading-tight">{step.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{step.text}</p></PaperSheet></ScrollReveal>)}</div></div></section>

    <section className="bg-[#dfeeff] px-4 py-20 sm:px-6"><div className="mx-auto max-w-5xl"><PaperSheet tone="yellow" className="p-8 sm:p-12" rotate={-1}><Tape color="cream" className="-top-3 right-16 rotate-6"/><div className="grid items-center gap-8 md:grid-cols-[1fr_auto]"><div><Target className="h-9 w-9 text-[#132d63]"/><h2 className="sbc-display mt-4 text-4xl font-black uppercase sm:text-5xl">Help us build what comes next.</h2><p className="mt-4 max-w-2xl leading-7 text-slate-700">Register a young builder, introduce SBC to a school or join us as a partner. The 2030 vision grows one learner, one mentor and one community at a time.</p></div><div className="flex flex-col gap-3"><Link href={path("/register")}><PaperButton className="w-full">{t("Register a learner")} <ArrowRight className="ml-2 h-5 w-5"/></PaperButton></Link><Link href={path("/partner")} className="rounded-2xl border-2 border-[#132d63] px-5 py-3 text-center font-black">{t("Partner with SBC")}</Link></div></div></PaperSheet></div></section>
  </main><SbcFooter/></SbcPageShell>
}
